name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node js
        uses: actions/setup-node@v1
        with:
          node-version: 14.3
      - name: Install dependencies
        run: make install-deps
      - name: Run linter
        run: make lint
      - name: Capture test coverage and send to CodeClimate
        uses: paambaati/codeclimate-action@v2.6.0
        with:
          coverageCommand: make test-coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

